#!/usr/bin/python3
import sys
import fileinput
import json

def p(obj):
    print(json.dumps(obj, indent=2))

def getInput():
    fileRows = []
    with open(sys.argv[1], 'r') as file:
        for line in file:
            fileRows.append(line.rstrip())
    
    return fileRows

# pass multiple lines
# 1 integer per line
def arrayOfIntFromList(input):
    rows = [int(c) for c in input]
    return rows

# pass multiple lines
# returns a 2 dimensional array
def arrayFromGridOfDigits(input):
    rows = []
    for line in input:
        rows.append([int(c) for c in list(line.strip())])
    return rows

# one line in returns an array
def arrayOfStrFromCSV(line):
    return list(line.strip().split(','))

# one line in returns an array
def arrayOfIntFromCSV(line):
    return [int(i) for i in line.strip().split(',')]
    
# one line in returns an array
def arrayOfWordsFromString(line):
    return list(line.strip().split())

def readData():
    rows = []
    for line in fileinput.input():
        # rows.append(line.strip())
        rows.append([int(c) for c in list(line.strip())])
        # [int(i) for i in line.strip().split(',')]

    return rows

def findBlankLine(lines):
    for i in range(len(lines)):
        if (lines[i].strip() == ""):
            return i

requiredFields = ['byr','iyr','eyr','hgt','hcl','ecl','pid']
def checkValid(p):
    for f in requiredFields:
        if f not in p:
            return False
    
    if ((1920 <= int(p["byr"]) <= 2002) and
        (2010 <= int(p["iyr"]) <= 2020) and
        (2020 <= int(p["eyr"]) <= 2030)):
        num,unit = p["hgt"][:-2],p["hgt"][-2:]
        if (((unit == "cm") and (150 <= int(num) <= 193)) or 
            ((unit == "in") and (59 <= int(num) <= 76))):
            hcl = p["hcl"]
            if ((len(hcl) == 7) and (hcl[0] == "#") and (all (c in "0123456789abcdef" for c in hcl[1:]))):
                if (p['ecl'] in ['amb', 'blu' ,'brn' ,'gry', 'grn', 'hzl', 'oth']):
                    if ((len(p["pid"]) == 9) and (p["pid"].isnumeric())):
                        return True

    return False



input = getInput()

# data = arrayFromGridOfDigits(input)
# p(data)

valid = 0
p = {}
for i in range(len(input)):
    words = arrayOfWordsFromString(input[i])
    for word in words:
        key,value = word.split(':')
        p[key] = value
    
    if ((i == len(input)-1) or (input[i+1].strip() == "")):
        if (checkValid(p)):
            valid += 1
        p = {}

print(valid)