#!/usr/bin/python3
import sys
import fileinput
import json

def p(obj):
    print(json.dumps(obj, indent=2))

def getInput():
    fileRows = []
    with open(sys.argv[1], 'r') as file:
        for line in file:
            fileRows.append(line.rstrip())
    
    return fileRows

# pass multiple lines
# 1 integer per line
def arrayOfIntFromList(input):
    rows = [int(c) for c in input]
    return rows

# pass multiple lines
# returns a 2 dimensional array
def arrayFromGridOfDigits(input):
    rows = []
    for line in input:
        rows.append([int(c) for c in list(line.strip())])
    return rows

# one line in returns an array
def arrayOfStrFromCSV(line):
    return list(line.strip().split(','))

# one line in returns an array
def arrayOfIntFromCSV(line):
    return [int(i) for i in line.strip().split(',')]
    
# one line in returns an array
def arrayOfWordsFromString(line):
    return list(line.strip().split())

def readData():
    rows = []
    for line in fileinput.input():
        # rows.append(line.strip())
        rows.append([int(c) for c in list(line.strip())])
        # [int(i) for i in line.strip().split(',')]

    return rows

def findBlankLine(lines):
    for i in range(len(lines)):
        if (lines[i].strip() == ""):
            return i

def keyInit(dict,key,initialValue):
    if (key not in dict):
        dict[key] = value


map = {
    'A': 'r',
    'B': 'p',
    'C': 's',
    'X': 'r',
    'Y': 'p',
    'Z': 's',
    }

def rpsScore(opponent,me):
    p(opponent)
    p(me)
    result=0
    if (me == 'r'):
        result = 1
    elif (me == 'p'):
        result = 2
    else:
        result = 3

    if (opponent == me):
        result += 3
    else:
        if ((opponent == 'r' and me =='p') or
            (opponent == 'p' and me =='s') or
            (opponent == 's' and me =='r')):
            result += 6
    return result

def rpsScore2(opponent,win):

    if (win == 'Y'):
        me = opponent
    elif (opponent == 'r'):
        if (win == 'X'):
            me = 's'
        else:
            me = 'p'
    elif (opponent == 'p'):
        if (win == 'X'):
            me = 'r'
        else:
            me = 's'
    elif (opponent == 's'):
        if (win == 'X'):
            me = 'p'
        else:
            me = 'r'


    p(opponent)
    p(me)
    result=0
    if (me == 'r'):
        result = 1
    elif (me == 'p'):
        result = 2
    else:
        result = 3

    if (opponent == me):
        result += 3
    else:
        if ((opponent == 'r' and me =='p') or
            (opponent == 'p' and me =='s') or
            (opponent == 's' and me =='r')):
            result += 6
    return result

input = getInput()

# data = arrayFromGridOfDigits(input)
# p(data)

score = 0
score2 = 0

for round in input:
    score += rpsScore(map[round[0]],map[round[2]])
    score2 += rpsScore2(map[round[0]],round[2])

p(score)
p(score2)