#!/usr/bin/python3
import sys
import fileinput
import json

def p(obj):
    print(json.dumps(obj, indent=2))

def getInput():
    fileRows = []
    with open(sys.argv[1], 'r') as file:
        for line in file:
            fileRows.append(line.rstrip())
    
    return fileRows

# pass multiple lines
# 1 integer per line
def arrayOfIntFromList(input):
    rows = [int(c) for c in input]
    return rows

# pass multiple lines
# returns a 2 dimensional array
def arrayFromGridOfDigits(input):
    rows = []
    for line in input:
        rows.append([int(c) for c in list(line.strip())])
    return rows

# one line in returns an array
def arrayOfStrFromCSV(line):
    return list(line.strip().split(','))

# one line in returns an array
def arrayOfWordsFromString(line):
    return list(line.strip().split())

# one line in returns an array
def arrayOfIntFromCSV(line):
    return [int(i) for i in line.strip().split(',')]
    
def readData():
    rows = []
    for line in fileinput.input():
        # rows.append(line.strip())
        rows.append([int(c) for c in list(line.strip())])
        # [int(i) for i in line.strip().split(',')]

    return rows

def findBlankLine(lines):
    for i in range(len(lines)):
        if (lines[i].strip() == ""):
            return i



input = getInput()

# data = arrayFromGridOfDigits(input)
# p(data)

validCount = 0
validCount2 = 0
for row in input:
    data = arrayOfWordsFromString(row)
    min,max = [int(i) for i in data[0].split('-')]
    letter = data[1][0]
    count = data[2].count(letter)
    if ((count >= min) and (count <= max)):
        validCount += 1
    if ((data[2][min-1] == letter) ^ (data[2][max-1] == letter)):
        validCount2 += 1

p(validCount)
p(validCount2)