#!/usr/bin/python3
import fileinput
import json

def readData():
    for line in fileinput.input():
        crabPos = [int(i) for i in line.strip().split(',')]
    return crabPos

def getMaxPos(crabPos):
    max = 0
    for i in range(len(crabPos)):
        if (crabPos[i] > max):
            max = crabPos[i]
    return max


crabPos = readData()

print(getMaxPos(crabPos))

fuelCost = []
for alignPos in range(getMaxPos(crabPos)+1):
    fc = 0
    for i in range(len(crabPos)):
        fc += abs(crabPos[i] - alignPos)
    fuelCost.append(fc)

# print(fuelCost)

print(len(fuelCost))

minFuelCost = None
minIndex = 0
for i in range(len(fuelCost)):
    # print("{},{}".format(i,fuelCost[i]))
    if ((minFuelCost is None) or (fuelCost[i] < minFuelCost)):
        minFuelCost = fuelCost[i]
        minIndex = i

print(minIndex)
print(fuelCost[minIndex])

