#!/usr/bin/python3
import fileinput

d = []
for line in fileinput.input():
	d.append(int(line))

print(len(d))

d3 = []
for i in range(0,len(d)-2):
	d3.append(d[i]+d[i+1]+d[i+2])
	print(d3[-1])

print(len(d3))

counter = 0
for i in range(1,len(d3)):
	if (d3[i] > d3[i-1]):
		counter += 1

print(counter)

