#!/usr/bin/python3
import sys
import fileinput
import json

def p(obj):
    print(json.dumps(obj, indent=2))

def getInput():
    fileRows = []
    with open(sys.argv[1], 'r') as file:
        for line in file:
            fileRows.append(line.rstrip())
    
    return fileRows

# pass multiple lines
# 1 integer per line
def arrayOfIntFromList(input):
    rows = [int(c) for c in input]
    return rows

# pass multiple lines
# returns a 2 dimensional array
def arrayFromGridOfDigits(input):
    rows = []
    for line in input:
        rows.append([int(c) for c in list(line.strip())])
    return rows

# one line in returns an array
def arrayOfStrFromCSV(line):
    return list(line.strip().split(','))

# one line in returns an array
def arrayOfIntFromCSV(line):
    return [int(i) for i in line.strip().split(',')]
    
# one line in returns an array
def arrayOfWordsFromString(line):
    return list(line.strip().split())

def readData():
    rows = []
    for line in fileinput.input():
        # rows.append(line.strip())
        rows.append([int(c) for c in list(line.strip())])
        # [int(i) for i in line.strip().split(',')]

    return rows

def findBlankLine(lines):
    for i in range(len(lines)):
        if (lines[i].strip() == ""):
            return i

def keyInit(dict,key,initialValue):
    if (key not in dict):
        dict[key] = value



input = getInput()

# data = arrayFromGridOfDigits(input)
# p(data)

data = arrayOfIntFromList(input)
data.append(0)
data.sort()
data.append(data[-1]+3)
#p(data)

c1 = 0
c3 = 0
co = 0
cl = []
for i in range(1,len(data)):
    diff = data[i] - data[i-1]
    cl.append(diff)
    if (diff == 1): 
        c1 += 1
    elif (diff == 3):
        c3 += 1
    else: 
        co += 1

p([c1,c3])
p(c1*c3)
p(cl)

count = 0
cl2 = []
for i in range(len(cl)):
    if ((i<len(cl)-1) and (cl[i] == 1)):
        count += 1
    else:
        cl2.append(count)
        count = 0
p(cl2)
cl2.sort()
p(cl2)

total = 1
for c in cl2:
    if (c>1):
        total *= ((c*(c-1)/2)+1)
#        if (c == 2):
#            total *= 2
#        if (c == 3):
#            total *= 4
#        if (c == 4):
#            total *= 7

print(total)
