#!/usr/bin/python3
import fileinput
import json

def readData():
    rows = []
    for line in fileinput.input():
        rows.append(line.strip())

    return rows

openers = "([{<"
closers = ")]}>"
corruptPoints = [3,57,1197,25137]
autoCompletePoints = [1,2,3,4]

rows = readData()

corruptScore = 0
autoCompleteScores = []
for row in rows:
    stack = []
    corrupted = False
    for char in list(row):
        try:
            openerIndex = openers.index(char)
        except:
            openerIndex = -1

        try:
            closersIndex = closers.index(char)
        except:
            closersIndex = -1
        
        if (openerIndex >= 0):
            stack.append(openerIndex)
        elif (closersIndex >= 0):
            if ((len(stack) == 0) or (closersIndex != stack[-1])):
                corrupted = True

                break
            stack.pop()
    if (corrupted):
        corruptScore += corruptPoints[closersIndex]
    elif (len(stack) > 0):
        autoCompleteScore = 0
        while (len(stack) > 0):
            autoCompleteScore = (autoCompleteScore * 5) + autoCompletePoints[stack[-1]]
            stack.pop()
        autoCompleteScores.append(autoCompleteScore)



print(corruptScore)

autoCompleteScores.sort()
print(autoCompleteScores[int((len(autoCompleteScores)-1)/2)])