#!/usr/bin/python3
import fileinput
import json

def readData():
    for line in fileinput.input():
        fishAge = [int(i) for i in line.strip().split(',')]
    fishAgeCount = [0] * 9
    for i in range(len(fishAge)):
        fishAgeCount[fishAge[i]] += 1
    return fishAgeCount

def processFish(fishAgeCount):
    zeros = fishAgeCount[0]
    for i in range(1,len(fishAgeCount)):
        fishAgeCount[i-1] = fishAgeCount[i]
    fishAgeCount[8] = zeros
    fishAgeCount[6] += zeros    

def countFish(fishAgeCount):
    total = 0
    for i in range(len(fishAgeCount)):
        total += fishAgeCount[i]
    return total
    

fishAgeCount = readData()

days = 256
for i in range(days):
    processFish(fishAgeCount)
    print(countFish(fishAgeCount))

