#!/usr/bin/python3
import sys
import fileinput
import json

def p(obj):
    print(json.dumps(obj, indent=2))

def getInput():
    fileRows = []
    with open(sys.argv[1], 'r') as file:
        for line in file:
            fileRows.append(line.rstrip())
    
    return fileRows

# pass multiple lines
# 1 integer per line
def arrayOfIntFromList(input):
    rows = [int(c) for c in input]
    return rows

# pass multiple lines
# returns a 2 dimensional array
def arrayFromGridOfDigits(input):
    rows = []
    for line in input:
        rows.append([int(c) for c in list(line.strip())])
    return rows

# one line in returns an array
def arrayOfStrFromCSV(line):
    return list(line.strip().split(','))

# one line in returns an array
def arrayOfIntFromCSV(line):
    return [int(i) for i in line.strip().split(',')]
    
# one line in returns an array
def arrayOfWordsFromString(line):
    return list(line.strip().split())

def readData():
    rows = []
    for line in fileinput.input():
        # rows.append(line.strip())
        rows.append([int(c) for c in list(line.strip())])
        # [int(i) for i in line.strip().split(',')]

    return rows

def findBlankLine(lines):
    for i in range(len(lines)):
        if (lines[i].strip() == ""):
            return i

def keyInit(dict,key,initialValue):
    if (key not in dict):
        dict[key] = value

def findDup(a,b):
    result = None
    for c in a:
        if (c in b):
            result = c
            break
    
    return result

def findBadge(a):
    result = None
    for c in a[0]:
        if (c in a[1] and c in a[2]):
            result = c
            break
    return result

def getPriority(c):
    result = ord(c)
    if (result >= 97):
        result -= 96
    else:
        result -= 38
    return result

def contains(a,b):
    result = False

    aMinStr,aMaxStr = a.split('-')
    aMin = int(aMinStr)
    aMax = int(aMaxStr)
    bMinStr,bMaxStr = b.split('-')
    bMin = int(bMinStr)
    bMax = int(bMaxStr)

    if ((aMin <= bMin and aMax >= bMax) or
        (bMin <= aMin and bMax >= aMax)):
        result = True
    
    return result
    
def overlaps(a,b):
    result = False

    aMinStr,aMaxStr = a.split('-')
    aMin = int(aMinStr)
    aMax = int(aMaxStr)
    bMinStr,bMaxStr = b.split('-')
    bMin = int(bMinStr)
    bMax = int(bMaxStr)

    if ((aMin <= bMin and aMax >= bMin) or
        (aMin <= bMax and aMax >= bMax) or
        (bMin <= aMin and bMax >= aMin) or
        (bMin <= aMax and bMax >= aMax)):
        result = True
    
    return result
    


input = getInput()

# data = arrayFromGridOfDigits(input)
# p(data)

count = 0
count2 = 0
for line in input:

    a,b = line.split(',')

    p(a)
    p(b)

    if (contains(a,b)):
        count += 1
    if (overlaps(a,b)):
        count2 += 1

p(count)
p(count2)


