#!/usr/bin/python3
import sys
import fileinput
import json
import math
import re
import copy
from datetime import datetime
import itertools

debug=True

def p(obj,timePrefix = False, newLine = True):
    if newLine:
        end = "\n"
    else:
        end = ""

    if timePrefix:
        now = datetime.now()
        print('{}: '.format(str(now.time()).split('.')[0]),end="")

    if type(obj) in [set,frozenset]:
        printableObj = list(obj)
    else:
        printableObj = obj

    if type(printableObj) in [str,int]:
        print(printableObj,end=end)
    else:
        if timePrefix:
            print('')
        print(json.dumps(printableObj, indent=2),end=end)

def pd(obj,timePrefix = False,newLine = True):
    if debug:
        p(obj,timePrefix=timePrefix,newLine=newLine)

def pdCharGrid(grid):
    if debug:
        for y in range(len(grid)):
            pd(''.join(grid[y]))

def wait():
    if debug:
        input("Press Enter to continue...")

def getInput():
    fileRows = []
    with open(sys.argv[1], 'r') as file:
        for line in file:
            fileRows.append(line.rstrip())
    
    return fileRows

# pass multiple lines
# 1 integer per line
def arrayOfIntFromList(input):
    rows = [int(c) for c in input]
    return rows

# pass multiple lines
# returns a 2 dimensional array
def arrayFromGridOfDigits(input):
    rows = []
    for line in input:
        rows.append([int(c) for c in list(line.strip())])
    return rows

# pass multiple lines
# returns a 2 dimensional array
def arrayFromGridOfSpaceSeparatedDigits(input):
    rows = []
    for line in input:
        rows.append([int(c) for c in list(line.split(" "))])
    return rows

# one line in returns an array
def arrayOfStrFromCSV(line):
    return list(line.strip().split(','))

# one line in returns an array
def arrayOfIntFromCSV(line):
    return [int(i) for i in line.strip().split(',')]
    
# one line in returns an array
def arrayOfWordsFromString(line):
    return list(line.strip().split())

def readData():
    rows = []
    for line in fileinput.input():
        # rows.append(line.strip())
        rows.append([int(c) for c in list(line.strip())])
        # [int(i) for i in line.strip().split(',')]

    return rows

def findBlankLine(lines):
    for i in range(len(lines)):
        if (lines[i].strip() == ""):
            return i

def keyInit(dict,key,initialValue):
    if (key not in dict):
        dict[key] = initialValue

def initGrid(xSize,ySize,obj):
    grid = []
    for y in range(ySize):
        row = []
        for x in range(xSize):
            row.append(copy.deepcopy(obj))
        grid.append(row)
    return grid

def getGrid(grid,x,y,outOfBoundsObj=None):
    result = None
    if x<0 or x>=len(grid[0]) or y<0 or y>=len(grid):
        result = outOfBoundsObj
    else:
        result = grid[y][x]
    return result

def setGrid(grid,x,y,obj):
    grid[y][x] = obj

def findGrid(grid,obj):
    for y in range(len(grid)):
        for x in range(len(grid[0])):
            if getGrid(grid,x,y) == obj:
                return x,y

def setBit(value,bit):
    return value | (1<<bit)

def clearBit(value,bit):
    return value & ~(1<<bit)

def getBit(value,bit):
    return value & 1 << bit != 0 

dirList = ["^",">","v","<"]
def nextPosition(x,y,d):
    nX = x
    nY = y
    if d == "^": 
        nY -= 1
    elif d == ">":
        nX += 1
    elif d == "v":
        nY += 1
    elif d == "<":
        nX -= 1
    else:
        raise ValueError

    return nX,nY

def parseInput(input):
    data = [int(a) for a in input]
    return data


def mix(sn,value):
    return sn ^ value

def prune(sn):
    return sn & 16777215

def prng(input): 
    sn = input
    sn = (sn << 6) ^ sn
    sn = sn & 16777215
    
    sn = (sn >> 5) ^ sn
    sn = sn & 16777215

    sn = (sn << 11) ^ sn
    sn = sn & 16777215
    return sn


debug = True

sourceInput = getInput()

# data = arrayFromGridOfDigits(sourceInput)
# p(data)

data = parseInput(sourceInput)
# pd(data)

# data = [123]

priceList = [[a%10] for a in data]
changeList = [[None] for i in range(len(data))]
patternList = [[None] for i in range(len(data))]
patternMax = {}

count = 2000
for i in range(count):
    for x in range(len(data)):
        a = prng(data[x])
        data[x] = a
        priceList[x].append(a%10)
        changeList[x].append(priceList[x][i+1] - priceList[x][i])
        if i < 3:
            patternList[x].append(None)
        else: 
            thisPattern = (changeList[x][i-2],changeList[x][i-1],changeList[x][i],changeList[x][i+1])
            patternList[x].append(thisPattern)
            keyInit(patternMax,thisPattern,0)
            patternMax[thisPattern] += priceList[x][i+1]


# pd(priceList)
# pd(changeList)
# pd(patternList)

allPatterns = set()
for x in range(len(data)):
    allPatterns.update(patternList[x])

allPatterns.remove(None)
pd(f"patterns to check: {len(allPatterns)}")
# pd(list(allPatterns))

maxSum = 0
counter = 0
for thisPattern in reversed(sorted(patternMax, key=patternMax.get)):
    counter += 1
    if counter % 1 == 0:
        pd(f"checking {counter}",timePrefix=True)
    if patternMax[thisPattern] < maxSum:
        break
    thisSum = 0
    for x in range(len(data)):
        try:
            thisIndex = patternList[x].index(thisPattern)
            thisSum += priceList[x][thisIndex]
        except ValueError:
            pass
    if thisSum > maxSum:
        maxSum = thisSum
        pd(maxSum)


pd(maxSum)