#!/usr/bin/python3
import fileinput

position = 0
depth = 0
aim = 0

for line in fileinput.input():
    inputs = line.split(' ')
    command = inputs[0]
    value = int(inputs[1])

    if (command == 'forward'):
        position += value
        depth += value * aim
    elif (command == 'down'):
        # depth += value
        aim += value
    elif (command == 'up'):
        # depth -= value
        aim -= value
    else:
        print("Error: " + line)

print(position)
print(depth)
print(position*depth)